SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE ROLE bill_daemon_local;
ALTER ROLE bill_daemon_local WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md50b11a11686f194f92e10fa9eb342771c';
CREATE ROLE bill_daemon_remote;
ALTER ROLE bill_daemon_remote WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md5169bc1d8d25a7a91c4e7e2e671631012';
CREATE ROLE doleynik_rw;
ALTER ROLE doleynik_rw WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION PASSWORD 'md50e8b9e7b3f46b35d180c8e2a5aa3cc59';
CREATE ROLE g_bill_daemon_local;
ALTER ROLE g_bill_daemon_local WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE g_bill_daemon_remote;
ALTER ROLE g_bill_daemon_remote WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE g_migrator;
ALTER ROLE g_migrator WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION VALID UNTIL 'infinity';
CREATE ROLE g_pgsync;
ALTER ROLE g_pgsync WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE g_readonly;
ALTER ROLE g_readonly WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION VALID UNTIL 'infinity';
CREATE ROLE g_stat;
ALTER ROLE g_stat WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE g_support;
ALTER ROLE g_support WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE g_voipgui;
ALTER ROLE g_voipgui WITH NOSUPERUSER NOINHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION;
CREATE ROLE pgsqltest;
ALTER ROLE pgsqltest WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md52a0bcc4c32b2f76f1e400fbc9c4dc853' VALID UNTIL 'infinity';
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION PASSWORD 'md58752ac2de0c80f50af998405db6a1278';
CREATE ROLE radius;
ALTER ROLE radius WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md5322bd0cc17d0a35e01116db405683fab';
CREATE ROLE readonly;
ALTER ROLE readonly WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md576baf430da25297e4826168f7f75a0e5';
CREATE ROLE stat;
ALTER ROLE stat WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md5839ef3eb4faab99fde662f7348ee0a7e';
CREATE ROLE voipgui;
ALTER ROLE voipgui WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md57a1a49d7ba6feb6ef4186c74ef8b154f';

GRANT g_bill_daemon_local TO bill_daemon_local GRANTED BY postgres;
GRANT g_bill_daemon_remote TO bill_daemon_remote GRANTED BY postgres;
GRANT g_readonly TO pgsqltest GRANTED BY postgres;
GRANT g_readonly TO readonly GRANTED BY postgres;
GRANT g_stat TO stat GRANTED BY postgres;
GRANT g_voipgui TO voipgui GRANTED BY postgres;

-- CREATE TABLESPACE reg_cdr OWNER doleynik_rw LOCATION '/var/lib/postgresql/reg_cdr';
-- CREATE TABLESPACE traf_flow OWNER postgres LOCATION '/var/lib/postgresql/traf_flow';
