FROM centos:7

USER root

RUN yum -y update
RUN yum -y install centos-release-scl-rh epel-release mc
RUN rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

RUN yum -y install git vim 

RUN yum install -y php56w php56w-cli php56w-curl php56w-gd php56w-json php56w-mcrypt php56w-mysqlnd php56w-pgsql php56w-readline php56w-xdebug php56w-xmlrpc php56w-mbstring

VOLUME /opt/voip_gui

RUN    cp -pf \
		/etc/httpd/conf/httpd.conf \
		/etc/httpd/conf/httpd.conf.default \
	&& sed -i \
		-e '/^KeepAlive .*$/d' \
		-e '/^MaxKeepAliveRequests .*$/d' \
		-e '/^KeepAliveTimeout .*$/d' \
		-e '/^ServerSignature On$/d' \
		-e '/^ServerTokens OS$/d' \
		/etc/httpd/conf/httpd.conf \
	&& truncate -s 0 \
		/etc/httpd/conf.d/autoindex.conf \
	&& chmod 444 \
		/etc/httpd/conf.d/autoindex.conf \
	&& truncate -s 0 \
		/etc/httpd/conf.d/welcome.conf \
	&& chmod 444 \
		/etc/httpd/conf.d/welcome.conf \
	&& { \
		echo ''; \
		echo '#'; \
		echo '# Custom configuration'; \
		echo '#'; \
		echo 'ServerName voip_gui:80'; \
		echo 'KeepAlive On'; \
		echo 'MaxKeepAliveRequests 200'; \
		echo 'KeepAliveTimeout 2'; \
		echo 'DocumentRoot "/opt/voip_gui/web"'; \
		echo '<Directory "/opt/voip_gui/web">'; \
		echo '  AllowOverride All'; \
		echo '  Require all granted'; \
		echo ''; \
		echo '</Directory>'; \
	} >> /etc/httpd/conf/httpd.conf

EXPOSE 80 
CMD ["/usr/sbin/httpd" , "-DFOREGROUND"]





