apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-files
data:
  nginx.conf: |
    user nginx;
    worker_processes 20;

    error_log /dev/stderr;

    events {
      worker_connections 1024;
    }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      index index.html

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      log_format combined_plus escape=json '{"time_local": "$time_local", '
                                          '"remote_addr": "$remote_addr", '
                                          '"remote_user": "$remote_user", '
                                          '"request": "$request", '
                                          '"status": "$status", '
                                          '"body_bytes_sent": "$body_bytes_sent", '
                                          '"request_time": "$request_time", '
                                          '"http_referrer": "$http_referer", '
                                          '"http_user_agent": "$http_user_agent"}';

      server {
        listen 80;
        server_name {{ .Values.ci_url }};
        charset utf-8;
        root /www;
        access_log /dev/stdout combined_plus;

        location /healthz {
          return 200;
          access_log off;
        }

        location / {
          proxy_set_header Host $host;
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
        }
      }
    }
  .pgpass: |
{{ .Files.Get ".werf/tmp/.pgpass" | indent 8 }}
  testdial_cfg.json: |
    {
      "ami": {
          "ip": {{ .Values.ami.ip | quote }},
          "port": {{ .Values.ami.port | quote }},
          "login": {{ .Values.ami.login | quote }},
          "password": {{ .Values.ami.password | quote }}
      },
      "hubs": {
          "11":"CFO",
          "12":"UFO",
          "13":"YUFO",
          "14":"PFO",
          "15":"SZFO",
          "16":"DVFO",
          "17":"SFO",
          "19":"AT",
          "20":"EU",
          "99":"MSK"
      },
      "channel": "Local/s@autocall-out/n",
      "extension": "s",
      "context": "autocall",
      "priority": 1,
      "waittime": 3000,
      "onlyConsoleLog": 1
    }
  config.local.php: |
    <?php
    return [
        'resources' => [
            'http://iberus.mcn.ru:8099/healthcheck',
            'http://iberus.mcn.ru:8032/test/healthcheck',
            'http://reg10.mcntelecom.ru:8032/test/healthcheck',
            'http://reg11.mcntelecom.ru:8032/test/healthcheck',
            'http://reg12.mcntelecom.ru:8032/test/healthcheck',
            'http://reg13.mcntelecom.ru:8032/test/healthcheck',
            'http://reg14.mcntelecom.ru:8032/test/healthcheck',
            'http://reg15.mcntelecom.ru:8032/test/healthcheck',
            'http://reg16.mcntelecom.ru:8032/test/healthcheck',
            'http://reg17.mcntelecom.ru:8032/test/healthcheck',
            'http://reg19.mcntelecom.ru:8032/test/healthcheck',
            'http://reg20.mcntelecom.ru:8032/test/healthcheck',
            'http://reg99.mcntelecom.ru:8032/test/healthcheck',
            ['url' => 'http://apibill.mcn.ru:8110/api/health/','title' => 'apibill01'],
            ['url' => 'http://apibill2.mcn.ru:8110/api/health/', 'title' => 'apibill02'],
            ['url' => 'http://reg99.mcntelecom.ru:8101/api/health/', 'title' => 'ocslte (Квотирующий биллер)'],
            ['url' => 'http://iberus.mcn.ru:8099/healthcheck', 'title' => 'pgsync'],
            'https://lk.mcn.ru/lk/statistics/index',
            ['url' => 'https://stat.mcn.ru/export/health/health_for_managers.json', 'title' => 'stat.mcn.ru (for managers)'],
            'https://vpbx.mcn.ru/vpbx/health',
            'https://stat.mcn.ru/export/health/health.json',
        ],
    ];


