{{- if (eq .Values.global.env "prod-env-ci") }}

{{ $_ := set . "pg_host" .Values.postgres_prod_env_ci.host }}
{{ $_ := set . "pg_user" .Values.postgres_prod_env_ci.user }}
{{ $_ := set . "pg_password" .Values.postgres_prod_env_ci.password }}
{{ $_ := set . "pg_db" .Values.postgres_prod_env_ci.db }}
{{ $_ := set . "pg_port" .Values.postgres_prod_env_ci.port }}

{{- end }}

{{- if (eq .Values.global.env "prod") }}

{{ $_ := set . "pg_host" .Values.postgres_prod.host }}
{{ $_ := set . "pg_user" .Values.postgres_prod.user }}
{{ $_ := set . "pg_password" .Values.postgres_prod.password }}
{{ $_ := set . "pg_db" .Values.postgres_prod.db }}
{{ $_ := set . "pg_port" .Values.postgres_prod.port }}

{{- end }}

{{- if (eq .Values.global.env "euprod") }}

{{ $_ := set . "pg_host" .Values.postgres_euprod.host }}
{{ $_ := set . "pg_user" .Values.postgres_euprod.user }}
{{ $_ := set . "pg_password" .Values.postgres_euprod.password }}
{{ $_ := set . "pg_db" .Values.postgres_euprod.db }}
{{ $_ := set . "pg_port" .Values.postgres_euprod.port }}

{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-files
data:
  voipgui.php.ini: |-
    [PHP]
    memory_limit = 4G
    post_max_size = 900M

    output_buffering = 0
    expose_php = On
    max_input_time = 300
    serialize_precision = 17
    max_input_vars = 100000
    max_file_uploads = 20
    max_input_nesting_level = 64
    upload_max_filesize = 500M
    error_reporting = 22517
    display_errors = On
    display_startup_errors = Off
    enable_dl = Off
    log_errors = On
    error_log = /dev/stdout
    max_execution_time = 1800
    report_memleaks = On
    variables_order = "EGPCS"
    request_order = "GP"
    date.timezone = "Europe/Moscow"

    mail.add_x_header = On
    zend.assertions = 1
    zend.exception_ignore_args = Off

    [Session]
    session.gc_maxlifetime = 14400
    ###

  www.conf: |
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    pm = dynamic
    pm.max_children = 256
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 35
    pm.max_requests = 1000

    slowlog = /var/log/php-fpm-slow.log

  db-local.php: |
    <?php

    return [
        'dsn' => 'pgsql:host={{ .pg_host }};dbname={{ .pg_db }};port={{ .pg_port }}',
        'username' => '{{ .pg_user }}',
        'password' => '{{ .pg_password }}'
    ];

  params.php: |
    <?php
    return [
        'adminEmail' => 'admin@example.com',
        'NnpCalculationApi' => '',
{{- if (eq .Values.global.env "prod") }}
        'isEuropean' => false,
        'testNumberLink' => 'http://reg10.mcntelecom.ru:8032/',
        'prefixListTypeSevenOpenLink' => 'http://reg10.mcntelecom.ru:8032/test/nnpcalc?cmd=showTypeSeven',
        'prefixListTypeSevenGenerateLink' => 'http://reg10.mcntelecom.ru:8032/test/nnpcalc?cmd=fillNNPPrefixList&type={type}&id={id}&ndc_token={token}',
{{- else if (eq .Values.global.env "euprod") }}
        'isEuropean' => true,
        'testNumberLink' => 'http://reg10.mcntelecom.hu:8032/',
        'prefixListTypeSevenOpenLink' => 'http://reg10.mcntelecom.hu:8032/test/nnpcalc?cmd=showTypeSeven',
        'prefixListTypeSevenGenerateLink' => 'http://reg10.mcntelecom.hu:8032/test/nnpcalc?cmd=fillNNPPrefixList&type={type}&id={id}&ndc_token={token}',
{{- end }}
        'commentMaxLength' => 2048,
        'loggingEnabled' => true,
        'logReadMethods' => true,
        's3' => [
            'access_key' => '0FGDZKFU070KVOGACRUE',
            'secret_key' => 'UpikFKTR7pmhnenKE1lRWGkhgiCtBDdkTsB30EwT',
            'host' => 'rados.mcn.ru',
            'bucket_name' => 'autocaller',
            'use_ssl' => true,
        ],
    ];

  nginx.conf: |

    user www-data www-data;

    worker_processes auto;

    error_log /dev/stderr;

    events {
        worker_connections 4096;
    }

  
    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      index index.html

      client_max_body_size 2000M;

      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      set_real_ip_from  10.0.0.0/8;
      set_real_ip_from  172.0.0.0/8;
      set_real_ip_from  192.168.0.0/16;

      fastcgi_buffers 16 16k;
      fastcgi_buffer_size 32k;
      proxy_buffer_size   128k;
      proxy_buffers   4 256k;
      proxy_busy_buffers_size   256k;

      real_ip_header X-Real-IP;
      real_ip_recursive on;

      log_format combined_plus escape=json '{"time_local": "$time_local", '
                                          '"remote_addr": "$remote_addr", '
                                          '"remote_user": "$remote_user", '
                                          '"request": "$request", '
                                          '"status": "$status", '
                                          '"body_bytes_sent": "$body_bytes_sent", '
                                          '"request_time": "$request_time", '
                                          '"http_referrer": "$http_referer", '
                                          '"http_user_agent": "$http_user_agent"}';

      server {
        listen 80;
        server_name {{ .Values.ci_url }};
        root /opt/voip_gui/web;
        index index.php;

        charset utf-8;
        access_log /dev/stdout combined_plus;

        proxy_connect_timeout       1800;
        proxy_send_timeout          1800;
        proxy_read_timeout          1800;

        fastcgi_send_timeout        1800;
        fastcgi_read_timeout        1800;

        client_header_timeout       1800;
        client_body_timeout         1800;
        send_timeout                1800;

        location /healthz {
          return 200;
          access_log off;
        }

        location ~ [^/]\.php(/|$) {
          fastcgi_split_path_info ^(.+?\.php)(/.*)$;
          fastcgi_pass 127.0.0.1:9000;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_param PATH_INFO       $fastcgi_path_info;
        }

        location / {
          client_max_body_size    2000M;
          try_files $uri @php;
          index  index.html index.htm;
        }

        location @php {
          fastcgi_pass 127.0.0.1:9000;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $document_root/index.php;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
        }

        location {{ .Values.finding_nispd.host }} {
          proxy_pass http://127.0.0.1:{{ .Values.finding_nispd.port }};
        }
      }
    }
{{- if (eq .Values.global.env "dev") }}
  .pgpass: |
{{ .Files.Get ".werf/tmp/.pgpass" | indent 8 }}
{{- end }}
  testdial_cfg.json: |
    {
      "ami": {
          "ip": {{ .Values.ami.ip | quote }},
          "port": {{ .Values.ami.port | quote }},
          "login": {{ .Values.ami.login | quote }},
          "password": {{ .Values.ami.password | quote }}
      },
{{- if (eq .Values.global.env "prod") }}
      "hubs": {
          "11":"CFO",
          "12":"UFO",
          "13":"YUFO",
          "14":"PFO",
          "15":"SZFO",
          "16":"DVFO",
          "17":"SFO",
          "19":"AT",
          "20":"EU",
          "99":"MSK"
      },
{{- end }}
{{- if (eq .Values.global.env "euprod") }}
      "hubs": {
          "19":"AT",
          "20":"EU"
      },
{{- end }}
      "channel": "Local/s@autocall-out/n",
      "extension": "s",
      "context": "autocall",
      "priority": 1,
      "waittime": 3000,
      "onlyConsoleLog": 1
    }
  
{{- if (eq .Values.global.env "prod") }}
  config.local.php: |
      <?php
      return [
        'resources' => [
            'http://iberus.mcn.ru:8099/healthcheck',
            'http://reg10.mcntelecom.ru:8032/test/healthcheck',
            'http://reg11.mcntelecom.ru:8032/test/healthcheck',
            'http://reg12.mcntelecom.ru:8032/test/healthcheck',
            'http://reg13.mcntelecom.ru:8032/test/healthcheck',
            'http://reg14.mcntelecom.ru:8032/test/healthcheck',
            'http://reg15.mcntelecom.ru:8032/test/healthcheck',
            'http://reg16.mcntelecom.ru:8032/test/healthcheck',
            'http://reg17.mcntelecom.ru:8032/test/healthcheck',
            'http://reg19.mcntelecom.ru:8032/test/healthcheck',
            'http://reg20.mcntelecom.ru:8032/test/healthcheck',
            'http://reg99.mcntelecom.ru:8032/test/healthcheck',
            ['url' => 'http://apibill.mcn.ru:8110/api/health/','title' => 'apibill01'],
            ['url' => 'http://apibill2.mcn.ru:8110/api/health/', 'title' => 'apibill02'],
            ['url' => 'http://reg99.mcntelecom.ru:8101/api/health/', 'title' => 'ocslte (Квотирующий биллер)'],
            ['url' => 'http://iberus.mcn.ru:8099/healthcheck', 'title' => 'pgsync'],
            'https://lk.mcn.ru/lk/statistics/index',
            ['url' => 'https://stat.mcn.ru/export/health/health_for_managers.json', 'title' => 'stat.mcn.ru (for managers)'],
            'https://vpbx.mcn.ru/vpbx/health',
            'https://stat.mcn.ru/export/health/health.json',
        ],
      ];
{{- end }}
{{- if (eq .Values.global.env "euprod") }}
  config.local.php: |
      <?php
      return [
        'resources' => [
            'http://reg19.mcntelecom.hu:8032/test/healthcheck',
            'http://reg20.mcntelecom.hu:8032/test/healthcheck',
            'http://reg10.mcntelecom.hu:8032/test/healthcheck',
            'https://vpbx.kompaas.tech/vpbx/health',
            'https://stat.kompaas.tech/export/health/health.json',
        ],
      ];
{{- end }}
  finding_nispd_config.json: |
    {
      "pg_user": "{{ .pg_user }}",
      "pg_password": "{{ .pg_password }}",
      "pg_hostname": "{{ .pg_host }}",
      "pg_port": "{{ .pg_port }}",
      "pg_dbname": "{{ .pg_db }}"
    }
