{{- if (eq .Values.werf.env "dev") }}
{{- else }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend-prod
spec:
  replicas: {{- if (eq .Values.werf.env "dev") }} 1 {{- else }} 2 {{- end }}
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-backend-prod
  strategy: 
       type: RollingUpdate
  template:
    metadata:
      labels:
        ingressInternal: "yes"
        ingressExternal: "no"
        app: {{ .Chart.Name }}-backend-prod
{{- if (eq .Values.werf.env "prod") }}
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
            {
              "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [{
                  "labelSelector": {
                    "matchExpressions": [{
                      "key": "app",
                      "operator": "In",
                      "values": ["{{ .Chart.Name }}-backend-prod"]
                    }]
                  },
                  "topologyKey": "kubernetes.io/hostname"
                }]
              }
            }
{{- end }}
    spec:
      initContainers:
      - name: busybox-helper
        image: busybox:1.28
        command:  ['ln', '-f', '-s', '/opt/voip_gui/web/assets2/healthData.json', '/opt/voip_gui/web/assets/healthData.json']
        volumeMounts:
        - name: assets
          mountPath: /opt/voip_gui/web/assets
        - name: shared-healthdata
          mountPath: /opt/voip_gui/web/assets2
      containers:
      - name: nginx
        image: {{ .Values.werf.image.voip_gui_nginx_prod }}
        volumeMounts:
        - name: config-volume
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        - name: assets
          mountPath: /opt/voip_gui/web/assets
        - name: shared-healthdata
          mountPath: /opt/voip_gui/web/assets2
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
      - name: php-health-check-prod
        image: {{ .Values.werf.image.php_health_check_prod }}
        volumeMounts:
        - name: config-volume
          subPath: config.local.php
          mountPath: /app/health/config.local.php
        - name: shared-healthdata
          mountPath: /app/assets
      - name: php-fpm
        resources:
          limits:
            memory: "18Gi"
          requests:
            memory: "1Gi"
        image: {{ .Values.werf.image.voip_gui_php_fpm_prod }}
        volumeMounts:
        - name: config-volume
          subPath: voipgui.php.ini
          mountPath: /usr/local/etc/php/conf.d/voipgui.php.ini
        - name: config-volume
          subPath: www.conf
          mountPath: /usr/local/etc/php-fpm.d/www.conf
        - name: config-volume
          subPath: config.local.php
          mountPath: /opt/voip_gui/web/health/config.local.php
        - name: shared-healthdata
          mountPath: /opt/voip_gui/web/assets2
        - name: assets
          mountPath: /opt/voip_gui/web/assets
        - name: config-volume
          subPath: db-local.php
          mountPath: /opt/voip_gui/config/db-local.php
        - name: config-volume
          subPath: params.php
          mountPath: /opt/voip_gui/config/params.php
        env:
        - name: TEST_DIAL_URL
          value: "http://127.0.0.1:3000/"
      - name: testcall-daemon-prod
        image: {{ .Values.werf.image.testcall_daemon_prod }}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          subPath: testdial_cfg.json
          mountPath: /app/testdialer/testdial_cfg.json
      - name: finding-nispd-chains
        workingDir: /app/finding_nispd/
        command: [ "python3", "print_chains.py" ]
        image: {{ .Values.werf.image.finding_nispd }}
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          subPath: finding_nispd_config.json
          mountPath: /app/finding_nispd/finding_nispd_config.json
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: shared-healthdata
        emptyDir: {}
      - name: assets
        emptyDir: {}
{{- if (eq .Values.werf.env "prod") }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workertype
                operator: In
                values:
                - virtual
                - baremetal
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-prod
  labels:
    app: {{ .Chart.Name }}-backend-prod
spec:
  selector:
    app: {{ .Chart.Name }}-backend-prod
  ports:
  - name: http
    port: 80
    protocol: TCP

{{- end }}
