{{- if (eq .Values.global.env "dev") }}
{{- else }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend-prod
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-backend-prod
  template:
    metadata:
      labels:
        ingressInternal: "yes"
        ingressExternal: "no"
        app: {{ .Chart.Name }}-backend-prod
    spec:
      containers:
      - name: backend-prod
{{ tuple "voip-gui-prod" . | werf_container_image | indent 8 }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          subPath: config.local.php
          mountPath: /opt/voip_gui/web/health/config.local.php 
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres_prod.db }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres_prod.host }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres_prod.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_prod.password }}
        - name: TEST_DIAL_URL
          value: "http://{{ .Chart.Name }}-testdial-daemon-prod:3000/"
{{ tuple . | werf_container_env | indent 8 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-prod
  labels:
    app: {{ .Chart.Name }}-backend-prod
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-backend-prod
  ports:
  - name: http
    port: 80
    protocol: TCP


{{- end }}
