{{- if (eq .Values.global.env "dev") }}
{{- else }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend-prod
spec:
  replicas: 1
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-backend-prod
  strategy: 
       type: RollingUpdate
  template:
    metadata:
      labels:
        ingressInternal: "yes"
        ingressExternal: "no"
        app: {{ .Chart.Name }}-backend-prod
    spec:
      containers:
      - name: nginx
{{ tuple "nginx" . | include "werf_container_image" | indent 8 }}
        volumeMounts:
        - name: config-volume
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
      - name: php-health-check-prod
{{ tuple "php-health-check-prod" . | werf_container_image | indent 8 }}
        volumeMounts:
        - name: config-volume
          subPath: config.local.php
          mountPath: /app/health/config.local.php
        - name: shared-healthdata
          mountPath: /app/assets
      - name: backend-prod
{{ tuple "voip-gui-prod" . | werf_container_image | indent 8 }}
        resources:
          requests:
            memory: 4G
          limits:
            memory: 6G
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        volumeMounts:
        - name: config-volume
          subPath: config.local.php
          mountPath: /opt/voip_gui/web/health/config.local.php 
        - name: shared-healthdata
          mountPath: /opt/voip_gui/web/assets2
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres_prod.db }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres_prod.host }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres_prod.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_prod.password }}
        - name: TEST_DIAL_URL
          value: "http://127.0.0.1:3000/"
      - name: testcall-daemon-prod
{{ tuple "testcall-daemon-prod" . | werf_container_image | indent 8 }}
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: config-volume
          subPath: testdial_cfg.json
          mountPath: /app/testdialer/testdial_cfg.json  
        env:
{{ tuple . | werf_container_env | indent 8 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: shared-healthdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-prod
  labels:
    app: {{ .Chart.Name }}-backend-prod
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-backend-prod
  ports:
  - name: http
    port: 80
    protocol: TCP

{{- end }}
