{{- if (eq .Values.global.env "dev") }}


---
kind: Secret
apiVersion: v1
metadata:
  name: secret-dev
data:
  id_rsa: {{ .Files.Get ".werf/tmp/id_rsa" | b64enc }}
  .pgpass: {{ .Files.Get ".werf/tmp/.pgpass" | b64enc }}
type: Opaque

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-backend-dev
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}-backend-dev
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-backend-dev
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend-dev
        ingressInternal: "yes"
        ingressExternal: "no"
    spec:
      initContainers:
      - name: wait-pod-postgres
        image: busybox:1.28
        command:  ['sh', '-c', "until nslookup {{ .Values.postgres_env_ci.host }}; do echo waiting for postgres; sleep 2; done"]
      - name: wait-postgres-ready
        image: postgres:12
        command:
          - "sh"
          - "-c"
          - "until pg_isready -h {{ .Values.postgres_env_ci.host }} -U {{ .Values.postgres_env_ci.adminuser }} -p {{ .Values.postgres_env_ci.port }}; do sleep 2; done;"
      containers:
      - name: nginx
{{ tuple (printf "%s-%s" .Chart.Name "nginx-dev") . | werf_container_image | indent 8 }}
        volumeMounts:
        - name: config-volume
          subPath: nginx.conf
          mountPath: /etc/nginx/nginx.conf
        - mountPath: /workspace
          name: workspace-voipgui
        - mountPath: /opt
          name: opt-voipgui
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx", "-s", "quit"]
      - name: php-fpm
{{ tuple (printf "%s-%s" .Chart.Name "php-fpm-dev") . | werf_container_image | indent 8 }}
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres_env_ci.db }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres_env_ci.host }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres_env_ci.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_env_ci.password }}
        volumeMounts:
        - name: config-volume
          subPath: voipgui.php.ini
          mountPath: /usr/local/etc/php/conf.d/voipgui.php.ini
        - name: config-volume
          subPath: www.conf
          mountPath: /usr/local/etc/php-fpm.d/www.conf
        - name: config-volume
          subPath: db-local.php
          mountPath: /db-local.php
        - mountPath: /workspace
          name: workspace-voipgui
        - mountPath: /opt
          name: opt-voipgui
        - name: secret
          mountPath: "/root/.ssh/id_rsa"  
          subPath: "id_rsa"
        - name: secret
          mountPath: "/root/.pgpass_b"  
          subPath: ".pgpass"
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-config-files
      - name: secret
        secret:
            secretName: secret-dev
            defaultMode: 0600          
      restartPolicy: Always
  volumeClaimTemplates:           
  - metadata:
      name: opt-voipgui
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Mi      
  - metadata:
      name: workspace-voipgui
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi      
          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-dev
  labels:
    app: {{ .Chart.Name }}-backend-dev
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-backend-dev
  ports:
  - name: http
    port: 80
    protocol: TCP
---
{{- else }}

{{- end }}
