{{- if (eq .Values.global.env "dev") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-backend-dev
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}-backend-dev
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-backend-dev
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-backend-dev
        ingressInternal: "yes"
        ingressExternal: "no"
    spec:
      initContainers:
      - name: wait-pod-postgres
        image: busybox:1.28
        command:  ['sh', '-c', "until nslookup {{ .Values.postgres_dev.host }}.{{ .Chart.Name }}-{{ .Values.global.env }}.svc.cluster.local; do echo waiting for postgres; sleep 2; done"]
      - name: wait-postgres-ready
        image: postgres:12
        command:
          - "sh"
          - "-c"
          - "until pg_isready -h {{ .Values.postgres_dev.host }} -U {{ .Values.postgres_dev.adminuser }} -p {{ .Values.postgres_dev.port }}; do sleep 2; done;"
      containers:
      - name: backend-dev
{{ tuple "voip-gui-dev" . | werf_container_image | indent 8 }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 80
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres_dev.db }}
        - name: POSTGRES_HOST
          value: {{ .Values.postgres_dev.host }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres_dev.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres_dev.password }}
{{ tuple . | werf_container_env | indent 8 }}
        volumeMounts:
        - mountPath: /workspace
          name: workspace-voipgui
        - mountPath: /root/.pgpass_b
          name: config-files
          mode: 
          subPath: .pgpass
      volumes:
      - name: workspace-voipgui
        hostPath:
          path: /.volumes/workspace-voipgui
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-config-files
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-dev
  labels:
    app: {{ .Chart.Name }}-backend-dev
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-backend-dev
  ports:
  - name: http
    port: 80
    protocol: TCP
---
{{- else }}

{{- end }}
