{{- if (eq .Values.global.env "dev") }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres_dev.host }}
spec:
  selector:
    matchLabels:
      service: {{ .Values.postgres_dev.host }}
  replicas: 1
  serviceName: {{ .Values.postgres_dev.host }}
  template:
    metadata:
      labels:
        service: {{ .Values.postgres_dev.host }}
    spec:
      containers:
      - name: {{ .Values.postgres_dev.host }}
        image: postgres:12
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres_dev.adminuser }}
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-db-pv-claim
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-db-pv-claim
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres_dev.host }}
  labels:
    service: {{ .Values.postgres_dev.host }}
spec:
  ports:
  - name: "5432"
    port: 5432
  selector:
    service: {{ .Values.postgres_dev.host }}
{{- else }}

{{- end }}
